# Generated by Django 3.0.2 on 2020-01-07 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200107_2043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post post', 'verbose_name_plural': 'Post posts'},
        ),
    ]
